/**
 * Simplified Accounting System (SAS)
 * <h3>How to generate API clients and server stubs:</h3>java -jar <a href='http://119.15.88.122:8989/swagger-codegen-cli-2.3.1.jar' target='_blank'>swagger-codegen-cli-2.3.1.jar</a> generate -l typescript-angular -i http://119.15.88.122:8989/v2/api-docs -o /Users/sangkhim/Desktop/swagger<h3>LANGUAGES:</h3>-l typescript-angular (Angular)<br />-l javascript (React)<br />-l java (Android)<br />-l kotlin (Android)<br />-l objc (Objective C)<br />-l swift4 (Swift 4)
 *
 * OpenAPI spec version: API
 * Contact: info@udaya-tech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ResponseMessageOauthToken } from '../model/responseMessageOauthToken';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthControllerService {

    protected basePath = 'http://119.15.88.122:8989';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * login
     * 
     * @param password password
     * @param username username
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginUsingPOST(password: string, username: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseMessageOauthToken>;
    public loginUsingPOST(password: string, username: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseMessageOauthToken>>;
    public loginUsingPOST(password: string, username: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseMessageOauthToken>>;
    public loginUsingPOST(password: string, username: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling loginUsingPOST.');
        }
        if (username === null || username === undefined) {
            throw new Error('Required parameter username was null or undefined when calling loginUsingPOST.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (password !== undefined) {
            queryParameters = queryParameters.set('password', <any>password);
        }
        if (username !== undefined) {
            queryParameters = queryParameters.set('username', <any>username);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<ResponseMessageOauthToken>(`${this.basePath}/api/v1/auth/login`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
